### ISSUE TITLE
README_MB.02_02.txt - rename and move to Exercise FIles/02_02 

### ISSUE THREAD

**Issue by tcd1558** [tcd1558/SeleniumEssentialTraining#4]
Rename the file to MB_README.02_02.txt and move the file to SeleniumEssentialTraining/src/SeleniumEssentialTraining/Ex_Files_Selenium_EssT/Exercise Files/02_02

**Comment by tcd1558g** [comment]
I am working on this ..

**Comment by tcd1558g** [comment]
Issue #4 has been resolved in QA_20210203

**Comment by tcd1558** [comment]
Approved.
